### ISSUE TITLE
Connect multiple temperature sensors to Raspberry Pi.

### ISSUE THREAD

**Issue by dyerlytle** [LowellObservatory/InspectorGadget#1]
We'll use the sensor unique serial numbers to identify which sensor is which.

See:

http://www.reuk.co.uk/wordpress/raspberry-pi/connect-multiple-temperature-sensors-with-raspberry-pi/

**Comment by dyerlytle** [comment]
I have two temp sensors connected and am reading the temps from both.  This is really quite easy to do and we can easily add a couple more sensors.

**Comment by astrobokonon** [comment]
Done as of 472cc7bd395bfdece355cb91118e07de0405c69e using the 'w1thermsensor' helper library rather than messing around with the bus path by hand; it makes the query code way shorter 

https://github.com/LowellObservatory/InspectorGadget/blob/472cc7bd395bfdece355cb91118e07de0405c69e/MesaMon/temperamental/temperamental.py#L20-L33
